FROM mcr.microsoft.com/devcontainers/go:1-1.23-bookworm

# [Opcional] Instalar ferramentas adicionais de sistema aqui
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <pacote>